name: phone_auth
description: A phone authentication tutorial.

version: 1.5.0+6

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/glogo.png
